apiVersion: v1
kind: Service
metadata:
  name: controller-manager-api-service
  namespace: system
  labels:
    app.kubernetes.io/name: acp
    app.kubernetes.io/managed-by: kustomize
spec:
  type: ClusterIP
  selector:
    control-plane: controller-manager
    app.kubernetes.io/name: acp
  ports:
  - name: api
    port: 8082
    targetPort: api
    protocol: TCP