datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Tempo
        type: tempo
        uid: tempo
        access: proxy
        url: http://tempo:3100
        isDefault: true
        version: 1
        editable: true
      - name: Prometheus
        type: prometheus
        uid: prometheus
        access: proxy
        url: http://prometheus-server:80
        isDefault: false
        version: 1
        editable: true
      - name: Loki
        type: loki
        uid: loki
        access: proxy
        url: http://loki:3100
        version: 1
        editable: true
        jsonData:
          maxLines: 1000

service:
  type: NodePort
  nodePort: 13000

persistence:
  enabled: true
  type: pvc
  size: 1Gi

adminPassword: admin

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: "default"
        orgId: 1
        folder: ""
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards

dashboards:
  default:
    acp-traces:
      json: |
        {
          "annotations": {
            "list": [
              {
                "builtIn": 1,
                "datasource": {
                  "type": "grafana",
                  "uid": "-- Grafana --"
                },
                "enable": true,
                "hide": true,
                "iconColor": "rgba(0, 211, 255, 1)",
                "name": "Annotations & Alerts",
                "type": "dashboard"
              }
            ]
          },
          "editable": true,
          "fiscalYearStartMonth": 0,
          "graphTooltip": 0,
          "id": 1,
          "links": [],
          "panels": [
            {
              "datasource": {
                "type": "prometheus",
                "uid": "prometheus"
              },
              "fieldConfig": {
                "defaults": {
                  "color": {
                    "mode": "palette-classic"
                  },
                  "custom": {
                    "axisCenteredZero": false,
                    "axisColorMode": "text",
                    "axisLabel": "Count",
                    "axisPlacement": "auto",
                    "barAlignment": 0,
                    "drawStyle": "line",
                    "fillOpacity": 10,
                    "gradientMode": "none",
                    "hideFrom": {
                      "legend": false,
                      "tooltip": false,
                      "viz": false
                    },
                    "lineInterpolation": "linear",
                    "lineWidth": 1,
                    "pointSize": 5,
                    "scaleDistribution": {
                      "type": "linear"
                    },
                    "showPoints": "never",
                    "spanNulls": false,
                    "stacking": {
                      "group": "A",
                      "mode": "none"
                    },
                    "thresholdsStyle": {
                      "mode": "off"
                    }
                  },
                  "mappings": [],
                  "thresholds": {
                    "mode": "absolute",
                    "steps": [
                      {
                        "color": "green",
                        "value": null
                      }
                    ]
                  },
                  "unit": "short"
                },
                "overrides": []
              },
              "gridPos": {
                "h": 8,
                "w": 12,
                "x": 0,
                "y": 0
              },
              "id": 3,
              "options": {
                "legend": {
                  "calcs": [],
                  "displayMode": "list",
                  "placement": "bottom",
                  "showLegend": true
                },
                "tooltip": {
                  "mode": "single",
                  "sort": "none"
                }
              },
              "targets": [
                {
                  "datasource": {
                    "type": "prometheus",
                    "uid": "prometheus"
                  },
                  "expr": "rate(taskrun_reconcile_count[5m])",
                  "legendFormat": "Reconciles/sec",
                  "refId": "A"
                },
                {
                  "datasource": {
                    "type": "prometheus",
                    "uid": "prometheus"
                  },
                  "expr": "rate(taskrun_phase_transition[5m])",
                  "legendFormat": "Phase Transitions/sec",
                  "refId": "B"
                },
                {
                  "datasource": {
                    "type": "prometheus",
                    "uid": "prometheus"
                  },
                  "expr": "rate(taskrun_error_count[5m])",
                  "legendFormat": "Errors/sec",
                  "refId": "C"
                },
                {
                  "datasource": {
                    "type": "prometheus",
                    "uid": "prometheus"
                  },
                  "expr": "histogram_quantile(0.95, sum(rate(taskrun_reconcile_duration_bucket[5m])) by (le))",
                  "legendFormat": "p95 Reconcile Duration",
                  "refId": "D"
                }
              ],
              "title": "TaskRun Controller Metrics",
              "type": "timeseries"
            },
            {
              "datasource": {
                "type": "prometheus",
                "uid": "prometheus"
              },
              "fieldConfig": {
                "defaults": {
                  "mappings": [],
                  "thresholds": {
                    "mode": "absolute",
                    "steps": [
                      {
                        "color": "green",
                        "value": null
                      }
                    ]
                  },
                  "unit": "none"
                }
              },
              "gridPos": {
                "h": 8,
                "w": 12,
                "x": 12,
                "y": 0
              },
              "id": 4,
              "options": {
                "colorMode": "value",
                "graphMode": "area",
                "justifyMode": "auto",
                "orientation": "auto",
                "reduceOptions": {
                  "calcs": ["lastNotNull"],
                  "fields": "",
                  "values": false
                }
              },
              "targets": [
                {
                  "datasource": {
                    "type": "prometheus",
                    "uid": "prometheus"
                  },
                  "expr": "sum(taskrun_phase_transition) by (to_phase)",
                  "legendFormat": "{{to_phase}}",
                  "refId": "A"
                }
              ],
              "title": "TaskRun Phase Distribution",
              "type": "stat"
            },
            {
              "datasource": {
                "type": "tempo",
                "uid": "tempo"
              },
              "fieldConfig": {
                "defaults": {
                  "custom": {
                    "align": "auto",
                    "displayMode": "auto",
                    "inspect": false
                  }
                }
              },
              "gridPos": {
                "h": 8,
                "w": 12,
                "x": 0,
                "y": 8
              },
              "id": 1,
              "options": {
                "showHeader": true,
                "sortBy": [
                  {
                    "desc": true,
                    "displayName": "Start Time"
                  }
                ]
              },
              "targets": [
                {
                  "datasource": {
                    "type": "tempo",
                    "uid": "tempo"
                  },
                  "limit": 20,
                  "query": "{resource.service.name=\"acp-controller\"}",
                  "queryType": "traceql",
                  "tableType": "traces"
                }
              ],
              "title": "Recent acp Controller Traces",
              "type": "table"
            },
            {
              "datasource": {
                "type": "tempo",
                "uid": "tempo"
              },
              "fieldConfig": {
                "defaults": {},
                "overrides": []
              },
              "gridPos": {
                "h": 12,
                "w": 24,
                "x": 0,
                "y": 8
              },
              "id": 2,
              "options": {
                "spanFilters": {
                  "filters": [
                    {
                      "id": "service-name",
                      "operator": "=",
                      "scope": "resource",
                      "tag": "service.name",
                      "value": "acp-controller"
                    }
                  ]
                },
                "view": "TraceView"
              },
              "title": "Trace Details",
              "type": "traces"
            }
          ],
          "refresh": "5s",
          "schemaVersion": 38,
          "style": "dark",
          "tags": ["acp"],
          "templating": {
            "list": []
          },
          "time": {
            "from": "now-15m",
            "to": "now"
          },
          "timepicker": {},
          "timezone": "",
          "title": "acp Traces",
          "uid": "acp-traces",
          "version": 1,
          "weekStart": ""
        }
