---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubechain.humanlayer.dev
  resources:
  - agents
  - llms
  - mcpservers
  - taskruns
  - taskruntoolcalls
  - tasks
  - tools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubechain.humanlayer.dev
  resources:
  - agents/status
  - llms/status
  - mcpservers/status
  - taskruns/status
  - taskruntoolcalls/status
  - tasks/status
  - tools/status
  verbs:
  - get
  - patch
  - update
