---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubechain.humanlayer.dev
  resources:
  - llms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubechain.humanlayer.dev
  resources:
  - llms/finalizers
  verbs:
  - update
- apiGroups:
  - kubechain.humanlayer.dev
  resources:
  - llms/status
  verbs:
  - get
  - patch
  - update
