loki:
  auth_enabled: false
  mode: "single"
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
    filesystem:
      chunks_directory: /var/loki/chunks
      rules_directory: /var/loki/rules
  config:
    ingester:
      wal:
        enabled: false
    schema_config:
      configs:
        - store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h
    storage_config:
      boltdb_shipper:
        active_index_directory: /var/loki/index
        cache_location: /var/loki/cache
        shared_store: filesystem
      filesystem:
        directory: /var/loki/chunks
  singleBinary:
    enabled: true
    replicas: 1
  monitoring:
    selfMonitoring:
      enabled: false
    lokiCanary:
      enabled: false
  test:
    enabled: false

sidecar:
  enabled: false

persistence:
  enabled: true
  size: 10Gi

serviceMonitor:
  enabled: true

service:
  type: NodePort
