datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Tempo
        type: tempo
        uid: tempo
        access: proxy
        url: http://tempo:3100
        isDefault: true
        version: 1
        editable: true
      - name: Prometheus
        type: prometheus
        uid: prometheus
        access: proxy
        url: http://prometheus-server:80
        isDefault: false
        version: 1
        editable: true
      - name: Loki
        type: loki
        uid: loki
        access: proxy
        url: http://loki:3100
        version: 1
        editable: true
        jsonData:
          maxLines: 1000

service:
  type: NodePort
  nodePort: 13000

persistence:
  enabled: true
  type: pvc
  size: 1Gi

adminPassword: admin

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: "default"
        orgId: 1
        folder: ""
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards

dashboards:
  default:
    traces:
      json: |
        {
        "annotations": {
          "list": [
            {
              "builtIn": 1,
              "datasource": {
                "type": "grafana",
                "uid": "-- Grafana --"
              },
              "enable": true,
              "hide": true,
              "iconColor": "rgba(0, 211, 255, 1)",
              "name": "Annotations & Alerts",
              "type": "dashboard"
            }
          ]
        },
        "editable": true,
        "fiscalYearStartMonth": 0,
        "graphTooltip": 0,
        "id": 1,
        "links": [],
        "panels": [
          {
            "datasource": {
              "type": "tempo",
              "uid": "tempo"
            },
            "fieldConfig": {
              "defaults": {},
              "overrides": []
            },
            "gridPos": {
              "h": 8,
              "w": 24,
              "x": 0,
              "y": 0
            },
            "id": 1,
            "options": {
              "spanFilters": {
                "criticalPathOnly": false,
                "matchesOnly": false,
                "serviceNameOperator": "=",
                "spanNameOperator": "="
              },
              "view": "TraceView"
            },
            "pluginVersion": "11.5.1",
            "targets": [
              {
                "datasource": {
                  "type": "tempo",
                  "uid": "tempo"
                },
                "limit": 20,
                "query": "{resource.service.name=\"python-random-service\"}",
                "queryType": "traceql",
                "refId": "A",
                "tableType": "traces"
              }
            ],
            "title": "Test Traces",
            "type": "table"
          },
          {
            "datasource": {
              "type": "prometheus",
              "uid": "prometheus"
            },
            "fieldConfig": {
              "defaults": {
                "color": {
                  "mode": "palette-classic"
                },
                "custom": {
                  "axisBorderShow": false,
                  "axisCenteredZero": false,
                  "axisColorMode": "text",
                  "axisLabel": "Ratio",
                  "axisPlacement": "auto",
                  "barAlignment": 0,
                  "barWidthFactor": 0.6,
                  "drawStyle": "line",
                  "fillOpacity": 10,
                  "gradientMode": "none",
                  "hideFrom": {
                    "legend": false,
                    "tooltip": false,
                    "viz": false
                  },
                  "insertNulls": false,
                  "lineInterpolation": "linear",
                  "lineWidth": 1,
                  "pointSize": 5,
                  "scaleDistribution": {
                    "type": "linear"
                  },
                  "showPoints": "never",
                  "spanNulls": false,
                  "stacking": {
                    "group": "A",
                    "mode": "none"
                  },
                  "thresholdsStyle": {
                    "mode": "off"
                  }
                },
                "mappings": [],
                "thresholds": {
                  "mode": "absolute",
                  "steps": [
                    {
                      "color": "green",
                      "value": null
                    }
                  ]
                },
              },
              "overrides": []
            },
            "gridPos": {
              "h": 8,
              "w": 24,
              "x": 0,
              "y": 0
            },
            "id": 3,
            "options": {
              "legend": {
                "calcs": [],
                "displayMode": "list",
                "placement": "bottom",
                "showLegend": true
              },
              "tooltip": {
                "hideZeros": false,
                "mode": "single",
                "sort": "none"
              }
            },
            "pluginVersion": "11.5.1",
            "targets": [
              {
                "datasource": {
                  "type": "prometheus",
                  "uid": "prometheus"
                },
                "editorMode": "code",
                "expr": "curl_test_metric_ratio",
                "legendFormat": "test metric",
                "range": true,
                "refId": "A"
              }
            ],
            "title": "Test Metrics",
            "type": "timeseries"
          },
          {
            "datasource": {
              "type": "loki",
              "uid": "loki"
            },
            "fieldConfig": {
              "defaults": {},
              "overrides": []
            },
            "gridPos": {
              "h": 8,
              "w": 24,
              "x": 0,
              "y": 8
            },
            "id": 4,
            "options": {
              "dedupStrategy": "none",
              "enableInfiniteScrolling": false,
              "enableLogDetails": true,
              "prettifyLogMessage": false,
              "showCommonLabels": false,
              "showLabels": false,
              "showTime": true,
              "sortOrder": "Descending",
              "wrapLogMessage": false
            },
            "pluginVersion": "11.5.1",
            "targets": [
              {
                "datasource": {
                  "type": "loki",
                  "uid": "loki"
                },
                "editorMode": "builder",
                "expr": "{service_name=\"curl-test-service\"} | json",
                "queryType": "range",
                "refId": "A"
              }
            ],
            "title": "Test Logs",
            "type": "logs"
          }
        ],
        "preload": true,
        "refresh": "5s",
        "schemaVersion": 40,
        "tags": [],
        "templating": {
          "list": []
        },
        "time": {
          "from": "now-15m",
          "to": "now"
        },
        "timepicker": {},
        "timezone": "",
        "title": "Test data",
        "uid": "aedak754t4uf4f",
        "version": 9,
        "weekStart": ""
        }
