apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
    extraPortMappings:
      # Grafana
      - containerPort: 13000
        hostPort: ${HOST_PORT_13000}
        listenAddress: "0.0.0.0"
        protocol: tcp
      # Prometheus
      - containerPort: 9090
        hostPort: ${HOST_PORT_9092}
        listenAddress: "0.0.0.0"
        protocol: tcp
      # ACP Controller Manager HTTP gateway
      - containerPort: 8082
        hostPort: ${HOST_PORT_8082}
        listenAddress: "0.0.0.0"
        protocol: tcp

kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        "service-node-port-range": "80-40000"
