apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
    extraPortMappings:
      # Kubernetes API Server
      - containerPort: 6443
        hostPort: ${KIND_APISERVER_PORT}
        listenAddress: "127.0.0.1"
        protocol: tcp
      # ACP Controller Manager HTTP gateway
      - containerPort: 8082
        hostPort: ${ACP_SERVER_PORT}
        listenAddress: "127.0.0.1"
        protocol: tcp

kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        "service-node-port-range": "80-40000"
