# This rule is not used by the project acp itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over acp.humanlayer.dev.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: acp
    app.kubernetes.io/managed-by: kustomize
  name: llm-admin-role
rules:
- apiGroups:
  - acp.humanlayer.dev
  resources:
  - llms
  verbs:
  - '*'
- apiGroups:
  - acp.humanlayer.dev
  resources:
  - llms/status
  verbs:
  - get
