---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - acp.humanlayer.dev
  resources:
  - agents
  - contactchannels
  - llms
  - mcpservers
  - toolcalls
  - tasks
  - tools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - acp.humanlayer.dev
  resources:
  - agents/status
  - contactchannels/status
  - llms/status
  - mcpservers/status
  - toolcalls/status
  - tasks/status
  - tools/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - acp.humanlayer.dev
  resources:
  - contactchannels/finalizers
  verbs:
  - update
