apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- acp_acp_llm.yaml
- acp_acp_agent.yaml
- acp_acp_task.yaml
- acp_acp_mcpserver.yaml
- acp_acp_contactchannel.yaml
- acp_acp_claude_agent.yaml
- acp_acp_claude_task.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
