extraScrapeConfigs: |
  - job_name: 'otel-collector'
    metrics_path: /metrics
    static_configs:
      - targets:
        - otel-collector-opentelemetry-collector:8889
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
server:
  service:
    nodePort: 9090
    type: NodePort
