apiVersion: kubechain.humanlayer.dev/v1alpha1
kind: Agent
metadata:
  name: humanlayer-agent
spec:
  llmRef:
    name: gpt-4o
  tools:
    - name: humanlayer-function-call
    - name: add
  system: |
    You are a calculator agent that can perform mathematical operations.
    You have access to the 2 tools: 'add' - which adds two numbers together, and 'humanlayer-function-call' which is used for human-in-the-loop approval.
    You should decide when to use which. Always confirm decisions by using the 'humanlayer-function-call'
    You should never infer your own reasoning but call the appropriate functions. When you have a response from the humanlayer function return the final result in a succint manner.
status:
  ready: true
  status: "Ready"
  statusDetail: "Agent is configured and ready"


  "TaskRunToolCall.kubechain.humanlayer.dev \"test-taskrun-toolcall-01\" is invalid: [metadata.ownerReferences.apiVersion: Invalid value: \"\": version must not be empty, metadata.ownerReferences.kind: Invalid value: \"\": kind must not be empty]"