apiVersion: kubechain.humanlayer.dev/v1alpha1
kind: Tool
metadata:
  name: humanlayer-function-call
spec:
  toolType: externalAPI
  name: humanlayer-function-call
  description: Execute a function call via the Humanlayer API
  parameters:
    type: object
    properties:
      run_id:
        type: string
        description: Unique identifier for this run
      fn:
        type: string
        description: The name of the function to call
      kwargs:
        type: object
        description: The arguments to pass to the function
    required:
      - run_id
      - fn
      - kwargs
  execute:
    externalAPI:
      url: "https://api.humanlayer.dev/humanlayer/v1/function_calls"
      method: "POST"
      requiresApproval: true
      credentialsFrom:
        name: humanlayer-api-credentials
        key: api-key
status:
  ready: true
  status: "Ready"
  statusDetail: "Tool is configured and ready to use"