apiVersion: kubechain.humanlayer.dev/v1alpha1
kind: Tool
metadata:
  name: add
spec:
  toolType: function
  name: add
  description: Add two numbers
  arguments:
    type: object
    properties:
      a:
        type: number
      b:
        type: number
    required:
      - a
      - b
  execute:
    builtin:
      name: add
