apiVersion: kubechain.humanlayer.dev/v1alpha1
kind: LLM
metadata:
  name: llm-sample
spec:
  provider: openai
  apiKeyFrom:
    secretKeyRef:
      name: openai-api-key
      key: OPENAI_API_KEY
  temperature: "0.7"
  maxTokens: 1000
