apiVersion: kubechain.humanlayer.dev/v1alpha1
kind: ContactChannel
metadata:
  labels:
    app.kubernetes.io/name: kubechain
    app.kubernetes.io/managed-by: kustomize
  name: contactchannel-sample
spec:
  # TODO(user): Add fields here
