name: Go CI

on:
  push:
    branches: [ "main" ]
    paths:
      - "kubechain/**"
      - ".github/workflows/go-ci.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "kubechain/**"
      - ".github/workflows/go-ci.yml"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true

      - name: Install golangci-lint
        working-directory: kubechain
        run: make golangci-lint

      - name: Check formatting
        working-directory: kubechain
        run: |
          make fmt
          if [[ -n $(git diff) ]]; then
            echo "::error::Code is not properly formatted. Run 'make fmt' locally."
            git diff
            exit 1
          fi

      - name: Run linter
        working-directory: kubechain
        run: make lint

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true

      - name: Run tests
        working-directory: kubechain
        run: make test

      - name: Upload test coverage
        uses: actions/upload-artifact@v4
        with:
          name: test-coverage
          path: kubechain/cover.out
          retention-days: 7

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true

      - name: Build
        working-directory: kubechain
        run: make build

  e2e-test:
    name: E2E Tests
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true

      - name: Setup KinD
        uses: helm/kind-action@v1.9.0
        with:
          cluster_name: kubechain-example-cluster
          config: kubechain-example/kind/kind-config.yaml

      - name: Build and load controller image
        working-directory: kubechain
        run: make docker-load-kind

      - name: Run e2e tests
        working-directory: kubechain
        env:
          KIND_CLUSTER: kubechain-example-cluster
        run: make test-e2e

  docker:
    name: Docker Build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [lint, test, build, e2e-test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        working-directory: kubechain
        run: make docker-build