namespace: default
resources:
- ../../config/default
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Add a direct patch to override the controller image
patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: controller:202504181016
  target:
    kind: Deployment
    name: controller-manager
- patch: |-
    - op: replace
      path: /spec/type
      value: NodePort
    - op: add
      path: /spec/ports/0/nodePort
      value: 8082
  target:
    kind: Service
    name: controller-manager-api-service
images:
- name: controller
  newName: controller
  newTag: "202505121510"
