namespace: default
resources:
- ./service.yaml
- ../../config/default
images:
- name: controller
  newName: controller
  newTag: "202504171233"
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
