apiVersion: v1
kind: Service
metadata:
  name: controller-manager-service
spec:
  type: NodePort
  selector:
    control-plane: controller-manager
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 8082
      protocol: TCP
      name: http

